Added support for build and push package-scanner-cli
deepfence/package-scanner pull request #76
Opened 2024-05-22 17:44 UTC by akumars1

2024-05-23 06:29 UTC, gnmahanth approved these changes

2024-05-23 10:42 UTC, ramanan-ravi requested changes

2024-05-23 10:42 UTC, ramanan-ravi commented on Makefile
> +.PHONY: publish-packagescanner-cli
Rename to `publish-docker-cli`

2024-05-23 10:42 UTC, ramanan-ravi commented on Makefile
> +	docker build -t $(IMAGE_REPOSITORY)/deepfence_package_scanner_cli:$(DF_IMG_TAG) .
These can be removed. We already have `docker-cli`

2024-05-28 11:20 UTC, ramanan-ravi approved these changes

2024-05-28 11:20 UTC, merged